version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8080
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  elasticvue:
    image: cars10/elasticvue
    ports:
      - 8080:8080

  flask:
    build: ./flask
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - elasticsearch
      - elasticvue
      - flask
